RegWrite("HKCU\\TestHotKeys\\0\\code", 		0xbe0010,	"REG_DWORD")
RegWrite("HKCU\\TestHotKeys\\0\\IsScript",	1,			"REG_DWORD")
RegWrite("HKCU\\TestHotKeys\\0\\modul",		"Modul1")
RegWrite("HKCU\\TestHotKeys\\0\\macros",	"Macros1")

RegWrite("HKCU\\TestHotKeys\\1\\code", 		0x720000,	"REG_DWORD")
RegWrite("HKCU\\TestHotKeys\\1\\IsScript",	1,			"REG_DWORD")
RegWrite("HKCU\\TestHotKeys\\1\\modul",		"Modul2")
RegWrite("HKCU\\TestHotKeys\\1\\macros",	"Macros2")

RKM.RootKey = "HKCU\\TestHotKeys"

RKM.Load()
assign(RKM.Count(),2)

var hki = RKM.HotKeyInfo(0xbe0010)
assign((hki!=null), true)
assign(hki.Code, 0xbe0010)
assign(hki.IsScript, true)
assign(hki.Modul, "Modul1")
assign(hki.Macros, "Macros1")

var hki = RKM.HotKeyInfo(0x720000)
assign((hki!=null), true)
assign(hki.Code, 0x720000)
assign(hki.IsScript, true)
assign(hki.Modul, "Modul2")
assign(hki.Macros, "Macros2")

RegDelete("HKCU\\TestHotKeys\\1\\code")
RegDelete("HKCU\\TestHotKeys\\1\\IsScript")
RegDelete("HKCU\\TestHotKeys\\1\\modul")
RegDelete("HKCU\\TestHotKeys\\1\\macros")
RegDelete("HKCU\\TestHotKeys\\1\\")
RegDelete("HKCU\\TestHotKeys\\0\\code")
RegDelete("HKCU\\TestHotKeys\\0\\IsScript")
RegDelete("HKCU\\TestHotKeys\\0\\modul")
RegDelete("HKCU\\TestHotKeys\\0\\macros")
RegDelete("HKCU\\TestHotKeys\\0\\")
RegDelete("HKCU\\TestHotKeys\\")
