function CtrlF1() { HotKeyEventProxy.fireHotKeyEvent("CtrlF1") }
function AltF1() { HotKeyEventProxy.fireHotKeyEvent("AltF1") }
function ShiftF1() { HotKeyEventProxy.fireHotKeyEvent("ShiftF1") }
function CtrlAltF1() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF1") }
function CtrlShiftF1() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF1") }
function AltShiftF1() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF1") }
function CtrlAltShiftF1() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF1") }
function CtrlF2() { HotKeyEventProxy.fireHotKeyEvent("CtrlF2") }
function AltF2() { HotKeyEventProxy.fireHotKeyEvent("AltF2") }
function ShiftF2() { HotKeyEventProxy.fireHotKeyEvent("ShiftF2") }
function CtrlAltF2() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF2") }
function CtrlShiftF2() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF2") }
function AltShiftF2() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF2") }
function CtrlAltShiftF2() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF2") }
function CtrlF3() { HotKeyEventProxy.fireHotKeyEvent("CtrlF3") }
function AltF3() { HotKeyEventProxy.fireHotKeyEvent("AltF3") }
function ShiftF3() { HotKeyEventProxy.fireHotKeyEvent("ShiftF3") }
function CtrlAltF3() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF3") }
function CtrlShiftF3() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF3") }
function AltShiftF3() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF3") }
function CtrlAltShiftF3() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF3") }
function CtrlF4() { HotKeyEventProxy.fireHotKeyEvent("CtrlF4") }
function AltF4() { HotKeyEventProxy.fireHotKeyEvent("AltF4") }
function ShiftF4() { HotKeyEventProxy.fireHotKeyEvent("ShiftF4") }
function CtrlAltF4() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF4") }
function CtrlShiftF4() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF4") }
function AltShiftF4() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF4") }
function CtrlAltShiftF4() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF4") }
function CtrlF5() { HotKeyEventProxy.fireHotKeyEvent("CtrlF5") }
function AltF5() { HotKeyEventProxy.fireHotKeyEvent("AltF5") }
function ShiftF5() { HotKeyEventProxy.fireHotKeyEvent("ShiftF5") }
function CtrlAltF5() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF5") }
function CtrlShiftF5() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF5") }
function AltShiftF5() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF5") }
function CtrlAltShiftF5() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF5") }
function CtrlF6() { HotKeyEventProxy.fireHotKeyEvent("CtrlF6") }
function AltF6() { HotKeyEventProxy.fireHotKeyEvent("AltF6") }
function ShiftF6() { HotKeyEventProxy.fireHotKeyEvent("ShiftF6") }
function CtrlAltF6() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF6") }
function CtrlShiftF6() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF6") }
function AltShiftF6() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF6") }
function CtrlAltShiftF6() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF6") }
function CtrlF7() { HotKeyEventProxy.fireHotKeyEvent("CtrlF7") }
function AltF7() { HotKeyEventProxy.fireHotKeyEvent("AltF7") }
function ShiftF7() { HotKeyEventProxy.fireHotKeyEvent("ShiftF7") }
function CtrlAltF7() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF7") }
function CtrlShiftF7() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF7") }
function AltShiftF7() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF7") }
function CtrlAltShiftF7() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF7") }
function CtrlF8() { HotKeyEventProxy.fireHotKeyEvent("CtrlF8") }
function AltF8() { HotKeyEventProxy.fireHotKeyEvent("AltF8") }
function ShiftF8() { HotKeyEventProxy.fireHotKeyEvent("ShiftF8") }
function CtrlAltF8() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF8") }
function CtrlShiftF8() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF8") }
function AltShiftF8() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF8") }
function CtrlAltShiftF8() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF8") }
function CtrlF9() { HotKeyEventProxy.fireHotKeyEvent("CtrlF9") }
function AltF9() { HotKeyEventProxy.fireHotKeyEvent("AltF9") }
function ShiftF9() { HotKeyEventProxy.fireHotKeyEvent("ShiftF9") }
function CtrlAltF9() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF9") }
function CtrlShiftF9() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF9") }
function AltShiftF9() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF9") }
function CtrlAltShiftF9() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF9") }
function CtrlF10() { HotKeyEventProxy.fireHotKeyEvent("CtrlF10") }
function AltF10() { HotKeyEventProxy.fireHotKeyEvent("AltF10") }
function ShiftF10() { HotKeyEventProxy.fireHotKeyEvent("ShiftF10") }
function CtrlAltF10() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF10") }
function CtrlShiftF10() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF10") }
function AltShiftF10() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF10") }
function CtrlAltShiftF10() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF10") }
function CtrlF11() { HotKeyEventProxy.fireHotKeyEvent("CtrlF11") }
function AltF11() { HotKeyEventProxy.fireHotKeyEvent("AltF11") }
function ShiftF11() { HotKeyEventProxy.fireHotKeyEvent("ShiftF11") }
function CtrlAltF11() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF11") }
function CtrlShiftF11() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF11") }
function AltShiftF11() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF11") }
function CtrlAltShiftF11() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF11") }
function CtrlF12() { HotKeyEventProxy.fireHotKeyEvent("CtrlF12") }
function AltF12() { HotKeyEventProxy.fireHotKeyEvent("AltF12") }
function ShiftF12() { HotKeyEventProxy.fireHotKeyEvent("ShiftF12") }
function CtrlAltF12() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF12") }
function CtrlShiftF12() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF12") }
function AltShiftF12() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF12") }
function CtrlAltShiftF12() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF12") }
function CtrlPageUp() { HotKeyEventProxy.fireHotKeyEvent("CtrlPageUp") }
function AltPageUp() { HotKeyEventProxy.fireHotKeyEvent("AltPageUp") }
function ShiftPageUp() { HotKeyEventProxy.fireHotKeyEvent("ShiftPageUp") }
function CtrlAltPageUp() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltPageUp") }
function CtrlShiftPageUp() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftPageUp") }
function AltShiftPageUp() { HotKeyEventProxy.fireHotKeyEvent("AltShiftPageUp") }
function CtrlAltShiftPageUp() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftPageUp") }
function CtrlPageDown() { HotKeyEventProxy.fireHotKeyEvent("CtrlPageDown") }
function AltPageDown() { HotKeyEventProxy.fireHotKeyEvent("AltPageDown") }
function ShiftPageDown() { HotKeyEventProxy.fireHotKeyEvent("ShiftPageDown") }
function CtrlAltPageDown() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltPageDown") }
function CtrlShiftPageDown() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftPageDown") }
function AltShiftPageDown() { HotKeyEventProxy.fireHotKeyEvent("AltShiftPageDown") }
function CtrlAltShiftPageDown() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftPageDown") }
function CtrlEnd() { HotKeyEventProxy.fireHotKeyEvent("CtrlEnd") }
function AltEnd() { HotKeyEventProxy.fireHotKeyEvent("AltEnd") }
function ShiftEnd() { HotKeyEventProxy.fireHotKeyEvent("ShiftEnd") }
function CtrlAltEnd() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltEnd") }
function CtrlShiftEnd() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftEnd") }
function AltShiftEnd() { HotKeyEventProxy.fireHotKeyEvent("AltShiftEnd") }
function CtrlAltShiftEnd() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftEnd") }
function CtrlHome() { HotKeyEventProxy.fireHotKeyEvent("CtrlHome") }
function AltHome() { HotKeyEventProxy.fireHotKeyEvent("AltHome") }
function ShiftHome() { HotKeyEventProxy.fireHotKeyEvent("ShiftHome") }
function CtrlAltHome() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltHome") }
function CtrlShiftHome() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftHome") }
function AltShiftHome() { HotKeyEventProxy.fireHotKeyEvent("AltShiftHome") }
function CtrlAltShiftHome() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftHome") }
function CtrlLeft() { HotKeyEventProxy.fireHotKeyEvent("CtrlLeft") }
function AltLeft() { HotKeyEventProxy.fireHotKeyEvent("AltLeft") }
function ShiftLeft() { HotKeyEventProxy.fireHotKeyEvent("ShiftLeft") }
function CtrlAltLeft() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltLeft") }
function CtrlShiftLeft() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftLeft") }
function AltShiftLeft() { HotKeyEventProxy.fireHotKeyEvent("AltShiftLeft") }
function CtrlAltShiftLeft() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftLeft") }
function CtrlUp() { HotKeyEventProxy.fireHotKeyEvent("CtrlUp") }
function AltUp() { HotKeyEventProxy.fireHotKeyEvent("AltUp") }
function ShiftUp() { HotKeyEventProxy.fireHotKeyEvent("ShiftUp") }
function CtrlAltUp() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltUp") }
function CtrlShiftUp() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftUp") }
function AltShiftUp() { HotKeyEventProxy.fireHotKeyEvent("AltShiftUp") }
function CtrlAltShiftUp() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftUp") }
function CtrlRight() { HotKeyEventProxy.fireHotKeyEvent("CtrlRight") }
function AltRight() { HotKeyEventProxy.fireHotKeyEvent("AltRight") }
function ShiftRight() { HotKeyEventProxy.fireHotKeyEvent("ShiftRight") }
function CtrlAltRight() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltRight") }
function CtrlShiftRight() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftRight") }
function AltShiftRight() { HotKeyEventProxy.fireHotKeyEvent("AltShiftRight") }
function CtrlAltShiftRight() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftRight") }
function CtrlDown() { HotKeyEventProxy.fireHotKeyEvent("CtrlDown") }
function AltDown() { HotKeyEventProxy.fireHotKeyEvent("AltDown") }
function ShiftDown() { HotKeyEventProxy.fireHotKeyEvent("ShiftDown") }
function CtrlAltDown() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltDown") }
function CtrlShiftDown() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftDown") }
function AltShiftDown() { HotKeyEventProxy.fireHotKeyEvent("AltShiftDown") }
function CtrlAltShiftDown() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftDown") }
function CtrlNum0() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum0") }
function AltNum0() { HotKeyEventProxy.fireHotKeyEvent("AltNum0") }
function ShiftNum0() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum0") }
function CtrlAltNum0() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum0") }
function CtrlShiftNum0() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum0") }
function AltShiftNum0() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum0") }
function CtrlAltShiftNum0() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum0") }
function CtrlNum1() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum1") }
function AltNum1() { HotKeyEventProxy.fireHotKeyEvent("AltNum1") }
function ShiftNum1() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum1") }
function CtrlAltNum1() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum1") }
function CtrlShiftNum1() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum1") }
function AltShiftNum1() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum1") }
function CtrlAltShiftNum1() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum1") }
function CtrlNum2() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum2") }
function AltNum2() { HotKeyEventProxy.fireHotKeyEvent("AltNum2") }
function ShiftNum2() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum2") }
function CtrlAltNum2() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum2") }
function CtrlShiftNum2() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum2") }
function AltShiftNum2() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum2") }
function CtrlAltShiftNum2() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum2") }
function CtrlNum3() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum3") }
function AltNum3() { HotKeyEventProxy.fireHotKeyEvent("AltNum3") }
function ShiftNum3() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum3") }
function CtrlAltNum3() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum3") }
function CtrlShiftNum3() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum3") }
function AltShiftNum3() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum3") }
function CtrlAltShiftNum3() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum3") }
function CtrlNum4() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum4") }
function AltNum4() { HotKeyEventProxy.fireHotKeyEvent("AltNum4") }
function ShiftNum4() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum4") }
function CtrlAltNum4() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum4") }
function CtrlShiftNum4() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum4") }
function AltShiftNum4() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum4") }
function CtrlAltShiftNum4() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum4") }
function CtrlNum5() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum5") }
function AltNum5() { HotKeyEventProxy.fireHotKeyEvent("AltNum5") }
function ShiftNum5() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum5") }
function CtrlAltNum5() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum5") }
function CtrlShiftNum5() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum5") }
function AltShiftNum5() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum5") }
function CtrlAltShiftNum5() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum5") }
function CtrlNum6() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum6") }
function AltNum6() { HotKeyEventProxy.fireHotKeyEvent("AltNum6") }
function ShiftNum6() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum6") }
function CtrlAltNum6() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum6") }
function CtrlShiftNum6() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum6") }
function AltShiftNum6() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum6") }
function CtrlAltShiftNum6() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum6") }
function CtrlNum7() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum7") }
function AltNum7() { HotKeyEventProxy.fireHotKeyEvent("AltNum7") }
function ShiftNum7() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum7") }
function CtrlAltNum7() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum7") }
function CtrlShiftNum7() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum7") }
function AltShiftNum7() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum7") }
function CtrlAltShiftNum7() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum7") }
function CtrlNum8() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum8") }
function AltNum8() { HotKeyEventProxy.fireHotKeyEvent("AltNum8") }
function ShiftNum8() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum8") }
function CtrlAltNum8() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum8") }
function CtrlShiftNum8() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum8") }
function AltShiftNum8() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum8") }
function CtrlAltShiftNum8() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum8") }
function CtrlNum9() { HotKeyEventProxy.fireHotKeyEvent("CtrlNum9") }
function AltNum9() { HotKeyEventProxy.fireHotKeyEvent("AltNum9") }
function ShiftNum9() { HotKeyEventProxy.fireHotKeyEvent("ShiftNum9") }
function CtrlAltNum9() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltNum9") }
function CtrlShiftNum9() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftNum9") }
function AltShiftNum9() { HotKeyEventProxy.fireHotKeyEvent("AltShiftNum9") }
function CtrlAltShiftNum9() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftNum9") }
function Ctrl0x6a() { HotKeyEventProxy.fireHotKeyEvent("Ctrl0x6a") }
function Alt0x6a() { HotKeyEventProxy.fireHotKeyEvent("Alt0x6a") }
function Shift0x6a() { HotKeyEventProxy.fireHotKeyEvent("Shift0x6a") }
function CtrlAlt0x6a() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt0x6a") }
function CtrlShift0x6a() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift0x6a") }
function AltShift0x6a() { HotKeyEventProxy.fireHotKeyEvent("AltShift0x6a") }
function CtrlAltShift0x6a() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift0x6a") }
function Ctrl0x6b() { HotKeyEventProxy.fireHotKeyEvent("Ctrl0x6b") }
function Alt0x6b() { HotKeyEventProxy.fireHotKeyEvent("Alt0x6b") }
function Shift0x6b() { HotKeyEventProxy.fireHotKeyEvent("Shift0x6b") }
function CtrlAlt0x6b() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt0x6b") }
function CtrlShift0x6b() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift0x6b") }
function AltShift0x6b() { HotKeyEventProxy.fireHotKeyEvent("AltShift0x6b") }
function CtrlAltShift0x6b() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift0x6b") }
function Ctrl0x6d() { HotKeyEventProxy.fireHotKeyEvent("Ctrl0x6d") }
function Alt0x6d() { HotKeyEventProxy.fireHotKeyEvent("Alt0x6d") }
function Shift0x6d() { HotKeyEventProxy.fireHotKeyEvent("Shift0x6d") }
function CtrlAlt0x6d() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt0x6d") }
function CtrlShift0x6d() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift0x6d") }
function AltShift0x6d() { HotKeyEventProxy.fireHotKeyEvent("AltShift0x6d") }
function CtrlAltShift0x6d() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift0x6d") }
function Ctrl0x6e() { HotKeyEventProxy.fireHotKeyEvent("Ctrl0x6e") }
function Alt0x6e() { HotKeyEventProxy.fireHotKeyEvent("Alt0x6e") }
function Shift0x6e() { HotKeyEventProxy.fireHotKeyEvent("Shift0x6e") }
function CtrlAlt0x6e() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt0x6e") }
function CtrlShift0x6e() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift0x6e") }
function AltShift0x6e() { HotKeyEventProxy.fireHotKeyEvent("AltShift0x6e") }
function CtrlAltShift0x6e() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift0x6e") }
function Ctrl0x6f() { HotKeyEventProxy.fireHotKeyEvent("Ctrl0x6f") }
function Alt0x6f() { HotKeyEventProxy.fireHotKeyEvent("Alt0x6f") }
function Shift0x6f() { HotKeyEventProxy.fireHotKeyEvent("Shift0x6f") }
function CtrlAlt0x6f() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt0x6f") }
function CtrlShift0x6f() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift0x6f") }
function AltShift0x6f() { HotKeyEventProxy.fireHotKeyEvent("AltShift0x6f") }
function CtrlAltShift0x6f() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift0x6f") }
function Ctrl0() { HotKeyEventProxy.fireHotKeyEvent("Ctrl0") }
function Alt0() { HotKeyEventProxy.fireHotKeyEvent("Alt0") }
function CtrlAlt0() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt0") }
function CtrlShift0() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift0") }
function AltShift0() { HotKeyEventProxy.fireHotKeyEvent("AltShift0") }
function CtrlAltShift0() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift0") }
function Ctrl1() { HotKeyEventProxy.fireHotKeyEvent("Ctrl1") }
function Alt1() { HotKeyEventProxy.fireHotKeyEvent("Alt1") }
function CtrlAlt1() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt1") }
function CtrlShift1() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift1") }
function AltShift1() { HotKeyEventProxy.fireHotKeyEvent("AltShift1") }
function CtrlAltShift1() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift1") }
function Ctrl2() { HotKeyEventProxy.fireHotKeyEvent("Ctrl2") }
function Alt2() { HotKeyEventProxy.fireHotKeyEvent("Alt2") }
function CtrlAlt2() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt2") }
function CtrlShift2() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift2") }
function AltShift2() { HotKeyEventProxy.fireHotKeyEvent("AltShift2") }
function CtrlAltShift2() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift2") }
function Ctrl3() { HotKeyEventProxy.fireHotKeyEvent("Ctrl3") }
function Alt3() { HotKeyEventProxy.fireHotKeyEvent("Alt3") }
function CtrlAlt3() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt3") }
function CtrlShift3() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift3") }
function AltShift3() { HotKeyEventProxy.fireHotKeyEvent("AltShift3") }
function CtrlAltShift3() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift3") }
function Ctrl4() { HotKeyEventProxy.fireHotKeyEvent("Ctrl4") }
function Alt4() { HotKeyEventProxy.fireHotKeyEvent("Alt4") }
function CtrlAlt4() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt4") }
function CtrlShift4() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift4") }
function AltShift4() { HotKeyEventProxy.fireHotKeyEvent("AltShift4") }
function CtrlAltShift4() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift4") }
function Ctrl5() { HotKeyEventProxy.fireHotKeyEvent("Ctrl5") }
function Alt5() { HotKeyEventProxy.fireHotKeyEvent("Alt5") }
function CtrlAlt5() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt5") }
function CtrlShift5() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift5") }
function AltShift5() { HotKeyEventProxy.fireHotKeyEvent("AltShift5") }
function CtrlAltShift5() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift5") }
function Ctrl6() { HotKeyEventProxy.fireHotKeyEvent("Ctrl6") }
function Alt6() { HotKeyEventProxy.fireHotKeyEvent("Alt6") }
function CtrlAlt6() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt6") }
function CtrlShift6() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift6") }
function AltShift6() { HotKeyEventProxy.fireHotKeyEvent("AltShift6") }
function CtrlAltShift6() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift6") }
function Ctrl7() { HotKeyEventProxy.fireHotKeyEvent("Ctrl7") }
function Alt7() { HotKeyEventProxy.fireHotKeyEvent("Alt7") }
function CtrlAlt7() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt7") }
function CtrlShift7() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift7") }
function AltShift7() { HotKeyEventProxy.fireHotKeyEvent("AltShift7") }
function CtrlAltShift7() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift7") }
function Ctrl8() { HotKeyEventProxy.fireHotKeyEvent("Ctrl8") }
function Alt8() { HotKeyEventProxy.fireHotKeyEvent("Alt8") }
function CtrlAlt8() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt8") }
function CtrlShift8() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift8") }
function AltShift8() { HotKeyEventProxy.fireHotKeyEvent("AltShift8") }
function CtrlAltShift8() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift8") }
function Ctrl9() { HotKeyEventProxy.fireHotKeyEvent("Ctrl9") }
function Alt9() { HotKeyEventProxy.fireHotKeyEvent("Alt9") }
function CtrlAlt9() { HotKeyEventProxy.fireHotKeyEvent("CtrlAlt9") }
function CtrlShift9() { HotKeyEventProxy.fireHotKeyEvent("CtrlShift9") }
function AltShift9() { HotKeyEventProxy.fireHotKeyEvent("AltShift9") }
function CtrlAltShift9() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShift9") }
function CtrlA() { HotKeyEventProxy.fireHotKeyEvent("CtrlA") }
function AltA() { HotKeyEventProxy.fireHotKeyEvent("AltA") }
function CtrlAltA() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltA") }
function CtrlShiftA() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftA") }
function AltShiftA() { HotKeyEventProxy.fireHotKeyEvent("AltShiftA") }
function CtrlAltShiftA() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftA") }
function CtrlB() { HotKeyEventProxy.fireHotKeyEvent("CtrlB") }
function AltB() { HotKeyEventProxy.fireHotKeyEvent("AltB") }
function CtrlAltB() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltB") }
function CtrlShiftB() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftB") }
function AltShiftB() { HotKeyEventProxy.fireHotKeyEvent("AltShiftB") }
function CtrlAltShiftB() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftB") }
function CtrlC() { HotKeyEventProxy.fireHotKeyEvent("CtrlC") }
function AltC() { HotKeyEventProxy.fireHotKeyEvent("AltC") }
function CtrlAltC() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltC") }
function CtrlShiftC() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftC") }
function AltShiftC() { HotKeyEventProxy.fireHotKeyEvent("AltShiftC") }
function CtrlAltShiftC() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftC") }
function CtrlD() { HotKeyEventProxy.fireHotKeyEvent("CtrlD") }
function AltD() { HotKeyEventProxy.fireHotKeyEvent("AltD") }
function CtrlAltD() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltD") }
function CtrlShiftD() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftD") }
function AltShiftD() { HotKeyEventProxy.fireHotKeyEvent("AltShiftD") }
function CtrlAltShiftD() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftD") }
function CtrlE() { HotKeyEventProxy.fireHotKeyEvent("CtrlE") }
function AltE() { HotKeyEventProxy.fireHotKeyEvent("AltE") }
function CtrlAltE() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltE") }
function CtrlShiftE() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftE") }
function AltShiftE() { HotKeyEventProxy.fireHotKeyEvent("AltShiftE") }
function CtrlAltShiftE() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftE") }
function CtrlF() { HotKeyEventProxy.fireHotKeyEvent("CtrlF") }
function AltF() { HotKeyEventProxy.fireHotKeyEvent("AltF") }
function CtrlAltF() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltF") }
function CtrlShiftF() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftF") }
function AltShiftF() { HotKeyEventProxy.fireHotKeyEvent("AltShiftF") }
function CtrlAltShiftF() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftF") }
function CtrlG() { HotKeyEventProxy.fireHotKeyEvent("CtrlG") }
function AltG() { HotKeyEventProxy.fireHotKeyEvent("AltG") }
function CtrlAltG() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltG") }
function CtrlShiftG() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftG") }
function AltShiftG() { HotKeyEventProxy.fireHotKeyEvent("AltShiftG") }
function CtrlAltShiftG() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftG") }
function CtrlH() { HotKeyEventProxy.fireHotKeyEvent("CtrlH") }
function AltH() { HotKeyEventProxy.fireHotKeyEvent("AltH") }
function CtrlAltH() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltH") }
function CtrlShiftH() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftH") }
function AltShiftH() { HotKeyEventProxy.fireHotKeyEvent("AltShiftH") }
function CtrlAltShiftH() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftH") }
function CtrlI() { HotKeyEventProxy.fireHotKeyEvent("CtrlI") }
function AltI() { HotKeyEventProxy.fireHotKeyEvent("AltI") }
function CtrlAltI() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltI") }
function CtrlShiftI() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftI") }
function AltShiftI() { HotKeyEventProxy.fireHotKeyEvent("AltShiftI") }
function CtrlAltShiftI() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftI") }
function CtrlJ() { HotKeyEventProxy.fireHotKeyEvent("CtrlJ") }
function AltJ() { HotKeyEventProxy.fireHotKeyEvent("AltJ") }
function CtrlAltJ() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltJ") }
function CtrlShiftJ() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftJ") }
function AltShiftJ() { HotKeyEventProxy.fireHotKeyEvent("AltShiftJ") }
function CtrlAltShiftJ() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftJ") }
function CtrlK() { HotKeyEventProxy.fireHotKeyEvent("CtrlK") }
function AltK() { HotKeyEventProxy.fireHotKeyEvent("AltK") }
function CtrlAltK() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltK") }
function CtrlShiftK() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftK") }
function AltShiftK() { HotKeyEventProxy.fireHotKeyEvent("AltShiftK") }
function CtrlAltShiftK() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftK") }
function CtrlL() { HotKeyEventProxy.fireHotKeyEvent("CtrlL") }
function AltL() { HotKeyEventProxy.fireHotKeyEvent("AltL") }
function CtrlAltL() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltL") }
function CtrlShiftL() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftL") }
function AltShiftL() { HotKeyEventProxy.fireHotKeyEvent("AltShiftL") }
function CtrlAltShiftL() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftL") }
function CtrlM() { HotKeyEventProxy.fireHotKeyEvent("CtrlM") }
function AltM() { HotKeyEventProxy.fireHotKeyEvent("AltM") }
function CtrlAltM() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltM") }
function CtrlShiftM() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftM") }
function AltShiftM() { HotKeyEventProxy.fireHotKeyEvent("AltShiftM") }
function CtrlAltShiftM() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftM") }
function CtrlN() { HotKeyEventProxy.fireHotKeyEvent("CtrlN") }
function AltN() { HotKeyEventProxy.fireHotKeyEvent("AltN") }
function CtrlAltN() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltN") }
function CtrlShiftN() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftN") }
function AltShiftN() { HotKeyEventProxy.fireHotKeyEvent("AltShiftN") }
function CtrlAltShiftN() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftN") }
function CtrlO() { HotKeyEventProxy.fireHotKeyEvent("CtrlO") }
function AltO() { HotKeyEventProxy.fireHotKeyEvent("AltO") }
function CtrlAltO() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltO") }
function CtrlShiftO() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftO") }
function AltShiftO() { HotKeyEventProxy.fireHotKeyEvent("AltShiftO") }
function CtrlAltShiftO() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftO") }
function CtrlP() { HotKeyEventProxy.fireHotKeyEvent("CtrlP") }
function AltP() { HotKeyEventProxy.fireHotKeyEvent("AltP") }
function CtrlAltP() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltP") }
function CtrlShiftP() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftP") }
function AltShiftP() { HotKeyEventProxy.fireHotKeyEvent("AltShiftP") }
function CtrlAltShiftP() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftP") }
function CtrlQ() { HotKeyEventProxy.fireHotKeyEvent("CtrlQ") }
function AltQ() { HotKeyEventProxy.fireHotKeyEvent("AltQ") }
function CtrlAltQ() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltQ") }
function CtrlShiftQ() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftQ") }
function AltShiftQ() { HotKeyEventProxy.fireHotKeyEvent("AltShiftQ") }
function CtrlAltShiftQ() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftQ") }
function CtrlR() { HotKeyEventProxy.fireHotKeyEvent("CtrlR") }
function AltR() { HotKeyEventProxy.fireHotKeyEvent("AltR") }
function CtrlAltR() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltR") }
function CtrlShiftR() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftR") }
function AltShiftR() { HotKeyEventProxy.fireHotKeyEvent("AltShiftR") }
function CtrlAltShiftR() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftR") }
function CtrlS() { HotKeyEventProxy.fireHotKeyEvent("CtrlS") }
function AltS() { HotKeyEventProxy.fireHotKeyEvent("AltS") }
function CtrlAltS() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltS") }
function CtrlShiftS() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftS") }
function AltShiftS() { HotKeyEventProxy.fireHotKeyEvent("AltShiftS") }
function CtrlAltShiftS() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftS") }
function CtrlT() { HotKeyEventProxy.fireHotKeyEvent("CtrlT") }
function AltT() { HotKeyEventProxy.fireHotKeyEvent("AltT") }
function CtrlAltT() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltT") }
function CtrlShiftT() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftT") }
function AltShiftT() { HotKeyEventProxy.fireHotKeyEvent("AltShiftT") }
function CtrlAltShiftT() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftT") }
function CtrlU() { HotKeyEventProxy.fireHotKeyEvent("CtrlU") }
function AltU() { HotKeyEventProxy.fireHotKeyEvent("AltU") }
function CtrlAltU() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltU") }
function CtrlShiftU() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftU") }
function AltShiftU() { HotKeyEventProxy.fireHotKeyEvent("AltShiftU") }
function CtrlAltShiftU() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftU") }
function CtrlV() { HotKeyEventProxy.fireHotKeyEvent("CtrlV") }
function AltV() { HotKeyEventProxy.fireHotKeyEvent("AltV") }
function CtrlAltV() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltV") }
function CtrlShiftV() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftV") }
function AltShiftV() { HotKeyEventProxy.fireHotKeyEvent("AltShiftV") }
function CtrlAltShiftV() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftV") }
function CtrlW() { HotKeyEventProxy.fireHotKeyEvent("CtrlW") }
function AltW() { HotKeyEventProxy.fireHotKeyEvent("AltW") }
function CtrlAltW() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltW") }
function CtrlShiftW() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftW") }
function AltShiftW() { HotKeyEventProxy.fireHotKeyEvent("AltShiftW") }
function CtrlAltShiftW() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftW") }
function CtrlX() { HotKeyEventProxy.fireHotKeyEvent("CtrlX") }
function AltX() { HotKeyEventProxy.fireHotKeyEvent("AltX") }
function CtrlAltX() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltX") }
function CtrlShiftX() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftX") }
function AltShiftX() { HotKeyEventProxy.fireHotKeyEvent("AltShiftX") }
function CtrlAltShiftX() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftX") }
function CtrlY() { HotKeyEventProxy.fireHotKeyEvent("CtrlY") }
function AltY() { HotKeyEventProxy.fireHotKeyEvent("AltY") }
function CtrlAltY() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltY") }
function CtrlShiftY() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftY") }
function AltShiftY() { HotKeyEventProxy.fireHotKeyEvent("AltShiftY") }
function CtrlAltShiftY() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftY") }
function CtrlZ() { HotKeyEventProxy.fireHotKeyEvent("CtrlZ") }
function AltZ() { HotKeyEventProxy.fireHotKeyEvent("AltZ") }
function CtrlAltZ() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltZ") }
function CtrlShiftZ() { HotKeyEventProxy.fireHotKeyEvent("CtrlShiftZ") }
function AltShiftZ() { HotKeyEventProxy.fireHotKeyEvent("AltShiftZ") }
function CtrlAltShiftZ() { HotKeyEventProxy.fireHotKeyEvent("CtrlAltShiftZ") }
